### ISSUE TITLE
Choose starter theme

### ISSUE THREAD

**Issue by naomicbush** [wpgwinnett/planning#10]
* Sage 9
* _s
* Mythic
* WP Rig

_originally from #2_

**Comment by CarlaHabeeb** [comment]
I have been researching themes for a few months, and I would be interested to hear what the group thinks of the News Pro Theme by StudioPress

**Comment by naomicbush** [comment]
@CarlaHabeeb for this project, we're specifically looking for a **starter** theme we can use to build our own theme. StudioPress is a good company that provides pre-built _parent_ and _child_ themes.

**Comment by naomicbush** [comment]
We started with Mythic but ended up creating a Twenty Nineteen child theme
