### ISSUE TITLE
Choose CSS layout system

### ISSUE THREAD

**Issue by naomicbush** [wpgwinnett/planning#11]
* CSS Grid
* Flexbox
* Bootstrap
* Bulma
* Tailwind
* UI Kit

**Comment by selestiele** [comment]
I prefer CSS Grid, though I like the look of Bootstrap. I think, though, that Bootstrap tends to clutter the markup because of the classes. If we do choose Grid, I can help with this part. (I'm not as solid with Bootstrap, but I've used Grid on several sites).

**Comment by naomicbush** [comment]
@selestiele 👍 we're going with CSS Grid and Flexbox
