### ISSUE TITLE
Content plan

### ISSUE THREAD

**Issue by naomicbush** [wpgwinnett/planning#13]
Ideas (from 2014 issue #2)
* forums
* resource section, start here if you're new
* job listings (companies have been posting on AAWP)
* Twitter feed
* pull in from member blogs
* news/announcements

**Comment by selestiele** [comment]
Ooh. I like the job listings. Not *entirely* for personal reasons. How would that work?

**Comment by naomicbush** [comment]
@selestiele those are the old ideas — new plan is [here](https://github.com/wpgwinnett/planning/projects/1#column-3227166)

For job listings, we get local companies that contact us when they're looking for a WordPress developer or sometimes I'll tweet out positions from WordPress companies with remote jobs. So we'd include a place on our site for people to check for those.

**Comment by selestiele** [comment]
Ok. Thanks! I'm still new to the collaborative aspects of Github. :)

**Comment by naomicbush** [comment]
Working document from today's hack day:

https://docs.google.com/document/d/1MqMbvlxJo4WjWlUMlB8TxiIdA71H19yx9q9u3EfHHyQ/edit?usp=sharing
