### ISSUE TITLE
Choose events plugin

### ISSUE THREAD

**Issue by naomicbush** [wpgwinnett/planning#14]

**Comment by CarlaHabeeb** [comment]
I would like to suggest The Events Calenar by Modern Tribe

**Comment by CarlaHabeeb** [comment]
I have been researching events plugins for a few months, and I would be interested to hear what the group thinks of The Events Calendar plugin by Modern Tribe

**Comment by naomicbush** [comment]
Hi @CarlaHabeeb, that's the plugin we've chosen  😄

**Comment by naomicbush** [comment]
We tried the new version of Sugar and couldn't get it to work. We also tried Bill Erickson's simple Events calendar but it didn't have everything we needed. So we're using The Events Calendar.
