### ISSUE TITLE
Choose photo gallery plugin

### ISSUE THREAD

**Issue by naomicbush** [wpgwinnett/planning#16]

**Comment by selestiele** [comment]
Do we need a gallery plugin? If we use CSS grid, it's not hard to style our own gallery and stick with the default WP gallery. Or was there another reason to use a plugin?

**Comment by naomicbush** [comment]
@selestiele that was our consensus (to use the default WP galleries until we find a need for a full-fledged gallery plugin) :-) 

I created these issues to track our considerations and decision-making.

the only thing I could think of is if we want to show them in a lightbox, so something like https://wordpress.org/plugins/wp-featherlight/
