### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by naomicbush** [wpgwinnett/planning#2]
Our goal is to build and maintain this site openly, using as many free tools and professional practices as we can.

Here's what we need to get up-and-running:
- [x] **GitHub account** for keeping site in open-access version control
- [x] **hosting**
  the domain is currently pointed to a Multisite install on my VPS so it needs to be moved out and made into its own site. We can keep it on my VPS for now, or maybe spin up a cheap box on Digital Ocean (for anyone interested in server admin)? In the future, we can see about having our hosting sponsored (there's one company we love & mention every week).
- [x] **resources list**
  Divided by topic, starting with the things we've been mentioning every month — themes, plugins, how to start learning, hosting
- [ ] **version-controlled open content system**
  WP/GitHub content sync setup, so that contributing content is as simple as a pull request
  Resources:
  http://contribute.jquery.org/web-sites/
  http://learn.jquery.com/contributing/
  https://github.com/pods-framework/pods-code-library
  https://github.com/pods-framework/pods-code-library/blob/master/contributing.md
  https://github.com/pods-framework/grunt-wordpress-pods
- [ ] **repo structure**
  Will we keep entire site in version control? Should content be in a separate repo to segment contributions?
- [ ] **WordPress directory structure & management**
  I've been playing around with Composer and a modified version of the setups mentioned here http://roots.io/using-composer-with-wordpress/ and here http://composer.rarst.net/
- [ ] **Push & pull from Meetup API**
  http://www.meetup.com/meetup_api/ Everything should happen on our site and be pushed to Meetup
- [ ] **theme**
- [x] **forms plugin**
- [x] **mailing list**
- [ ] **BuddyPress**
  for member interaction
- [ ] **content plan**
  Ideas
  - forums (bbPress)
  - resource section, start here if you're new
  - job listings (companies have been posting on AAWP)
  - Twitter feed
  - pull in from member blogs
  - news/announcements
- [ ] **GitHub issue archiving on our site**
  using the GitHub API

If you can think of anything else, please comment. cc @wpgwinnett/organizers

**Comment by Swampson** [comment]
**resources list**: I can start working on this and organizing it with some introductory/explanatory text for each topic. @naomicbush, if you have any raw lists or notes from previous meetings, feel free to send them to me as-is and I can incorporate them into the first draft.

**Comment by naomicbush** [comment]
closing in favor of separate issues
